# -*- coding: utf-8 -*-
"""final exam 5th sem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOgmCUXd7RoOqW18exRFl8FJ-GkBa1lS
"""

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('/content/archive (1).zip')
print(data.head())
print(data.describe())
print(data.isnull().sum())

x = data.iloc[:, [3, 4]].values

wcss_list = []
for i in range(1, 11):
    kMeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kMeans.fit(X_scaled)
    wcss_list.append(kMeans.inertia_)

plt.plot(range(1, 11), wcss_list)
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.title('The Elbow Method')
plt.show()


kMeans = KMeans(n_clusters=3, init='k-means++', random_state=42)
y_kMeans = kMeans.fit_predict(X_scaled)
plt.scatter(X_scaled[y_kMeans == 0, 0], X_scaled[y_kMeans == 0, 1], s=100, color='green',label='cluster1')
plt.scatter(X_scaled[y_kMeans == 1, 0], X_scaled[y_kMeans == 1, 1], s=100, color='red',label='cluster2"')
plt.scatter(X_scaled[y_kMeans == 2, 0], X_scaled[y_kMeans == 2, 1], s=100, color='blue',label='cluster3')
plt.scatter(X_scaled[y_kMeans == 3, 0], X_scaled[y_kMeans == 3, 1], s=100, color='orange',label='cluster4')
plt.scatter(kMeans.cluster_centers_[:, 0], kMeans.cluster_centers_[:, 1], s=300, color='y',label='centroids')
plt.title('Clusters of customers')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.legend()
plt.show()

